name: alsat
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_storage: ^11.6.10
  firebase_messaging: ^14.7.16
  google_fonts: ^6.1.0
  provider: ^6.1.1
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/



