// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClp7J6nWaxpGw0Pdo31E1lSApHUgfK1Ws',
    appId: '1:132703937078:web:ed7f9b10d39ecdeb6dee97',
    messagingSenderId: '132703937078',
    projectId: 'alsat-83a41',
    authDomain: 'alsat-83a41.firebaseapp.com',
    storageBucket: 'alsat-83a41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmPBESFDhl631D_IrqYGP_t3H1lC5xQm0',
    appId: '1:132703937078:android:af5dcf571d35304d6dee97',
    messagingSenderId: '132703937078',
    projectId: 'alsat-83a41',
    storageBucket: 'alsat-83a41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXoCwCJTBhq0HMK3grAGyODq5nVXaRxqc',
    appId: '1:132703937078:ios:2fd3050fbc400bd06dee97',
    messagingSenderId: '132703937078',
    projectId: 'alsat-83a41',
    storageBucket: 'alsat-83a41.firebasestorage.app',
    iosBundleId: 'com.example.alsat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXoCwCJTBhq0HMK3grAGyODq5nVXaRxqc',
    appId: '1:132703937078:ios:2fd3050fbc400bd06dee97',
    messagingSenderId: '132703937078',
    projectId: 'alsat-83a41',
    storageBucket: 'alsat-83a41.firebasestorage.app',
    iosBundleId: 'com.example.alsat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClp7J6nWaxpGw0Pdo31E1lSApHUgfK1Ws',
    appId: '1:132703937078:web:8ee4b1ccdcc568ed6dee97',
    messagingSenderId: '132703937078',
    projectId: 'alsat-83a41',
    authDomain: 'alsat-83a41.firebaseapp.com',
    storageBucket: 'alsat-83a41.firebasestorage.app',
  );
}
